version: "3.7"
services:
  app:
    build:
      args:
        user: ${USER}
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: murtarl/sillion_challenge
    container_name: sillion_challenge
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sillion_challenge_network
  nginx:
    image: nginx:alpine
    container_name: nginx_sillion_challenge
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - sillion_challenge_network
networks:
  sillion_challenge_network:
    driver: bridge
